Repository Conrad-X/text2SQL, pull requests merged in 2024-09, with the labels that each got.

#2 docs: pull request templated added.
  server/docs/pull_request_template.md
Labels: documentation

#4 Feat: Create prompt factory
  README.md
  server/app/database_schema.py
  server/app/db.py
  server/app/main.py
  server/app/utils.py
  server/migrations/README
  server/seed_db.py
  server/services/anthropic_client.py
  server/services/base_client.py
  server/services/client_factory.py
  server/services/openai_client.py
  server/utilities/config.py
  server/utilities/constants/LLM_enums.py
  server/utilities/constants/prompts_enums.py
  server/utilities/constants/response_messages.py
  server/utilities/prompts/base_prompt.py
  server/utilities/prompts/few_shot_prompts.py
  server/utilities/prompts/prompt_factory.py
  server/utilities/prompts/zero_shot_prompts.py
  server/utilities/samples_questions_and_queries/hotel_schema.json
  server/utilities/utility_functions.py
Labels: enhancement

#5 Fix: Correct Spelling to 'dail sql' and Add LLM Name Prefix to Model Types
  server/app/main.py
  server/utilities/constants/LLM_enums.py
  server/utilities/constants/prompts_enums.py
  server/utilities/prompts/few_shot_prompts.py
  server/utilities/prompts/prompt_factory.py
Labels: bug

#6 docs: pull request template doc moved to the root
  docs/pull_request_template.md
Labels: documentation

#7 Feat: Create Masking Functions
  server/app/db.py
  server/app/main.py
  server/masked_sample_questions_and_queries/masked_hotel_schema.json
  server/nltk_downloader.py
  server/requirements.txt
  server/sample_questions_and_queries/hotel_schema.json
  server/utilities/config.py
  server/utilities/constants/response_messages.py
  server/utilities/prompts/base_prompt.py
  server/utilities/utility_functions.py
Labels: enhancement
