Repository Conrad-X/text2SQL, pull requests merged in 2024-10, with the labels that each got.

#9 Feat: Create 8-table Schema and Sample Questions Answers
  server/app/db.py
  server/app/models/healthcare_models.py
  server/data/masked_sample_questions_and_queries/masked_healthcare_schema.json
  server/data/sample_questions_and_queries/healthcare_schema.json
  server/data/seed_data/healthcare_seed_data.py
  server/databases/healthcare.db
  server/migrations/env.py
  server/utilities/constants/database_enums.py
Labels: enhancement

#10 Feat: Create 10-table Schema and Sample Questions Answers
  server/app/db.py
  server/app/models/music_festival_models.py
  server/data/masked_sample_questions_and_queries/masked_music_festival_schema.json
  server/data/sample_questions_and_queries/music_festival_schema.json
  server/data/seed_data/music_festival_seed_data.py
  server/databases/music_festival.db
  server/migrations/env.py
  server/utilities/constants/database_enums.py
  server/utilities/prompts/base_prompt.py
Labels: enhancement

#11 Feat(UI): Create Front-end for Text2SQL POC
  client/jsconfig.json
  client/package-lock.json
  client/package.json
  client/public/Text2SQLIcon.png
  client/public/index.html
  client/src/App.js
  client/src/components/ChatPanel/ChatPanel.css
  client/src/components/ChatPanel/ChatPanel.js
  client/src/components/ConfigurationPanel/ConfigurationPanel.css
  client/src/components/ConfigurationPanel/ConfigurationPanel.js
  client/src/components/ToastNotification/ToastNotification.css
  client/src/components/ToastNotification/ToastNotification.js
  client/src/constants/messages.js
  client/src/constants/promptEnums.js
  client/src/index.js
  client/src/pages/Text2Sql/Text2SQL.css
  client/src/pages/Text2Sql/Text2SQL.js
  server/app/main.py
  server/app/request_schema.py
  server/utilities/constants/response_messages.py
Labels: enhancement

#12 Feat: User dynamic database selection
  client/src/App.js
  client/src/components/ChatPanel/ChatPanel.js
  client/src/components/ConfigurationPanel/ConfigurationPanel.css
  client/src/components/ConfigurationPanel/ConfigurationPanel.js
  client/src/components/ToastNotification/ToastNotification.css
  client/src/components/ToastNotification/ToastNotification.js
  client/src/constants/databaseEnums.js
  client/src/constants/messages.js
  client/src/constants/toastType.js
  client/src/pages/Text2Sql/Text2SQL.js
  server/app/db.py
  server/app/main.py
  server/app/request_schema.py
  server/migrations/env.py
  server/utilities/config.py
  server/utilities/constants/response_messages.py
  server/utilities/prompts/base_prompt.py
  server/utilities/prompts/few_shot_prompts.py
  server/utilities/prompts/zero_shot_prompts.py
  server/utilities/utility_functions.py
Labels: enhancement, In Review

#15 feat: we added vector store support for few shot queries
  .gitignore
  server/app/main.py
  server/utilities/prompts/base_prompt.py
  server/utilities/vectorize.py
Labels: enhancement

#16 Feat: Integrate Query Similarity-Based Example Retrieval in Few-Shot Prompts
  server/utilities/constants/response_messages.py
  server/utilities/prompts/base_prompt.py
  server/utilities/vectorize.py
Labels: enhancement

#17 Refactor: Update Axios request to use serverUrl from .env
  client/src/components/ConfigurationPanel/ConfigurationPanel.js
  client/src/pages/Text2Sql/Text2SQL.js
Labels: documentation

#18 Fix: Push Missing PreviewModal.js Fille
  client/src/components/PreviewModal/PreviewModal.js
Labels: bug

#13 Test: Add unit tests for main.py
  server/app/db.py
  server/app/main.py
  server/app/request_schema.py
  server/test/__init__.py
  server/test/test_main.py
  server/utilities/config.py
  server/utilities/constants/response_messages.py
  server/utilities/utility_functions.py
Labels: enhancement

#20 Refactor: Made ChromaDB object Global
  .python-version
  server/app/main.py
  server/utilities/config.py
  server/utilities/prompts/base_prompt.py
  server/utilities/vectorize.py
Labels: enhancement

#22 Feat: Implement Cost Estimation
  server/app/main.py
  server/utilities/constants/LLM_enums.py
  server/utilities/constants/response_messages.py
  server/utilities/cost_estimation.py
Labels: enhancement
