Repository Conrad-X/text2SQL, pull requests merged in 2025-03, with the labels that each got.

#77 Feat: Update SQL Improver to Use Chat-Based LLM Prompting
  server/scripts/process_dataset_sequentially.py
  server/services/anthropic_client.py
  server/services/dashscope_client.py
  server/services/deepseek_client.py
  server/services/google_ai_client.py
  server/services/openai_client.py
  server/utilities/constants/prompts_enums.py
  server/utilities/prompts/prompt_templates.py
  server/utilities/sql_improvement.py
  server/utilities/utility_functions.py
Labels: enhancement

#78 Fix: Ensure Complete Vector Store Population in ChromaDB
  server/utilities/vectorize.py
Labels: bug

#71 Refiner bench
  server/data/bird/dev_20240627/dev_databases/refiner_bench_data.json
  server/scripts/process_dataset_sequentially.py
  server/scripts/refiner_bench.py
  server/utilities/candidate_selection.py
  server/utilities/logging_utils.py
  server/utilities/path_config.py
  server/utilities/sql_improvement.py
  server/utilities/utility_functions.py
Labels: enhancement

#79 Refactor: Prepare Codebase for Preprocessing for BIRD Evaluations
  server/preprocess/add_descriptions_bird_dataset.py
  server/preprocess/add_runtime_pruned_schema.py
  server/preprocess/prepare_sample_dataset.py
  server/preprocess/run/run_preprocess_test.sh
  server/preprocess/run/run_preprocess_train.sh
  server/utilities/config.py
  server/utilities/constants/database_enums.py
  server/utilities/path_config.py
Labels: enhancement

#81 Feat: Optimise SQL Refiner by Separating Error Fixing and Query Improvement Prompts
  server/utilities/prompts/prompt_templates.py
  server/utilities/sql_improvement.py
Labels: enhancement

#83 Feat: Add Predict SQLs Script for BIRD Submission
  server/predict_sqls/predict_sqls.py
  server/predict_sqls/run/run_predictions.sh
Labels: enhancement

#82 Refactor: Group SQL Candidates by Results Before Selection
  server/utilities/candidate_selection.py
Labels: enhancement

#84 Chore: Update requirements.txt Dependencies
  .python-version
  server/requirements.txt
Labels: enhancement

#85 Guard rails
  server/utilities/candidate_selection.py
  server/utilities/sql_improvement.py
  server/utilities/utility_functions.py
Labels: bug, enhancement

#86 Updated Readme
  README.md
Labels: documentation, draft

#91 Refactor: Use Longest Column Descriptions in Format Schemas
  server/utilities/m_schema/schema_engine.py
  server/utilities/utility_functions.py
Labels: enhancement

#94 Feat: Edit add_descriptions_bird_dataset to Handle Both Column Descriptions and Description CSV
  server/preprocess/add_descriptions_bird_dataset.py
Labels: enhancement

#93 Refactor: Update Codebase with Optimised Schema Pruning Prompt
  server/preprocess/add_runtime_pruned_schema.py
  server/utilities/prompts/prompt_templates.py
  server/utilities/schema_linking/schema_linking_utils.py
Labels: enhancement

#96 Feat: Exec results in Refiner Prompt now randomly sample and in markdown
  server/utilities/sql_improvement.py
Labels: enhancement

#97 Feat: Add Gemini 2.5 Pro Experimental model
  server/utilities/constants/LLM_enums.py
  server/utilities/llm_metrics/pricing.py
Labels: enhancement

#95 Refactor: Fix schema reference bug and improve code readability
  server/predict_sqls/predict_sqls.py
Labels: enhancement
