Repository Conrad-X/text2SQL, pull requests merged in 2025-05, with the labels that each got.

#109 Chore(Restructure Scripts Folder): Remove Cortex Analyst Related Scripts
  server/scripts/evaluate_cortex_analyst.py
Labels: chore

#110 Chore(Restructure Scripts Folder): Remove Snowflake Related Scripts
  server/scripts/data_migration_snowflake.py
  server/utilities/logging_utils.py
Labels: chore

#114 feat: add pre-commit hook for pep enforcing packages
  .editorconfig
  README.md
  server/.pre-commit-config.yaml
  server/requirements.txt
Labels: documentation, enhancement

#111 Backward Schema Linking With Internal Prompts
  server/utilities/schema_linking/schema_linking_utils.py
  server/utilities/utility_functions.py
Labels: enhancement

#118 feat: added pydocstyle to the repository
  README.md
  server/.pre-commit-config.yaml
  server/services/base_client.py
Labels: enhancement

#116 Refactor(Refactor Preprocessing Folder): Refactor Runtime Pruned Schema Script
  server/preprocess/add_runtime_pruned_schema.py
  server/utilities/bird_utils.py
  server/utilities/constants/LLM_enums.py
  server/utilities/constants/bird_utils/indexing_constants.py
  server/utilities/constants/bird_utils/response_messages.py
  server/utilities/constants/preprocess/add_runtime_pruned_schema/indexing_constants.py
  server/utilities/constants/preprocess/add_runtime_pruned_schema/response_messages.py
  server/utilities/schema_linking/schema_linking_utils.py
Labels: enhancement

#125 Add Coverall Badge
  README.md
Labels: documentation, chore

#127 Refactor(Refactoring): Refactor Services Folder
  .github/workflows/coverage.yaml
  server/app/main.py
  server/app/request_schema.py
  server/internal_benchmarks/candidate_selection/selection_bench.py
  server/internal_benchmarks/refiner/refiner_bench.py
  server/predict_sqls/predict_sqls.py
  server/preprocess/add_descriptions_bird_dataset.py
  server/preprocess/add_runtime_pruned_schema.py
  server/preprocess/prepare_sample_dataset.py
  server/scripts/cost_estimation_dataset.py
  server/scripts/estimate_costs.py
  server/scripts/process_dataset_sequentially.py
  server/services/anthropic_client.py
  server/services/base_client.py
  server/services/chat_formatter/anthropic_chat_formatter.py
  server/services/chat_formatter/base_chat_formatter.py
  server/services/chat_formatter/google_ai_chat_formatter.py
  server/services/chat_formatter/openai_chat_formatter.py
  server/services/client_factory.py
  server/services/clients/anthropic_client.py
  server/services/clients/base_client.py
  server/services/clients/client_factory.py
  server/services/clients/dashscope_client.py
  server/services/clients/deepseek_client.py
  server/services/clients/google_ai_client.py
  server/services/clients/openai_client.py
  server/services/dashscope_client.py
  server/services/deepseek_client.py
  server/services/google_ai_client.py
  server/services/openai_client.py
  server/services/utils/api_key_manager.py
  server/services/utils/call_retry_handler.py
  server/services/validators/model_validator.py
  server/test/preprocess/test_add_descriptions_bird_dataset.py
  server/test/preprocess/test_add_runtime_pruned_schema.py
  server/test/test_main.py
  server/utilities/config.py
  server/utilities/constants/response_messages.py
  server/utilities/constants/services/chat_format.py
  server/utilities/constants/services/indexing_constants.py
  server/utilities/constants/services/llm_enums.py
  server/utilities/constants/services/response_messages.py
  server/utilities/cost_estimation.py
  server/utilities/llm_metrics/pricing.py
  server/utilities/llm_metrics/token_calculator.py
  server/utilities/schema_linking/extract_keyword.py
  server/utilities/schema_linking/schema_linking_utils.py
  server/utilities/sql_improvement.py
  server/utilities/utility_functions.py
Labels: enhancement

#123 Refactor Format Schema
  server/app/main.py
  server/preprocess/add_descriptions_bird_dataset.py
  server/utilities/bird_utils.py
  server/utilities/candidate_selection.py
  server/utilities/constants/bird_utils/response_messages.py
  server/utilities/constants/common/indexing_constants.py
  server/utilities/constants/preprocess/add_descriptions_bird_dataset/response_messages.py
  server/utilities/constants/response_messages.py
  server/utilities/constants/utilities/format_schema/indexing_constants.py
  server/utilities/constants/utilities/format_schema/response_messages.py
  server/utilities/constants/utilities/format_schema/schema_templates.py
  server/utilities/format_schema.py
  server/utilities/prompts/few_shot_prompts.py
  server/utilities/prompts/zero_shot_prompts.py
  server/utilities/schema_linking/schema_linking_utils.py
  server/utilities/sql_improvement.py
  server/utilities/utility_functions.py
Labels: chore

#122 refactor: prepare_sample_dataset updated
  server/preprocess/prepare_sample_dataset.py
  server/scripts/mask_bird.py
  server/scripts/train_test_split_bird.py
  server/utilities/connections/common.py
  server/utilities/connections/sqlite.py
  server/utilities/constants/bird_utils/indexing_constants.py
  server/utilities/constants/common/error_messages.py
  server/utilities/constants/preprocess/prepare_sample_dataset/indexing_constants.py
  server/utilities/constants/preprocess/prepare_sample_dataset/response_messages.py
Labels: documentation, enhancement
