Repository Conrad-X/text2SQL, pull requests merged in 2025-02, with the labels that each got.

#46 Fix: Add separate client for Improvement prompt and move Improvment functions to Utilities
  server/scripts/process_dataset_sequentially.py
  server/services/client_factory.py
  server/utilities/sql_improvement.py
Labels: bug, enhancement

#47 Run Multiple Configs in process_dataset_sequentially
  server/app/main.py
  server/scripts/download_batch_output.py
  server/scripts/generate_batch_file.py
  server/scripts/process_batch_output.py
  server/scripts/process_dataset_sequentially.py
  server/services/base_client.py
  server/services/openai_client.py
  server/utilities/batch_job.py
  server/utilities/constants/response_messages.py
  server/utilities/constants/script_constants.py
  server/utilities/utility_functions.py
Labels: enhancement

#48 Prune Test Compares the gold pruned schema to runtime pruned schema
  server/scripts/prune_test.py
Labels: enhancement

#50 Improver Chat Implementation
  server/scripts/process_dataset_sequentially.py
  server/services/anthropic_client.py
  server/services/base_client.py
  server/services/deepseek_client.py
  server/services/google_ai_client.py
  server/services/openai_client.py
  server/utilities/sql_improvement.py
  server/utilities/utility_functions.py
Labels: enhancement

#51 Feat(retrieval): Integrate NER, Vectorization, and LSH for Schema Pruning
  server/app/main.py
  server/scripts/process_dataset_sequentially.py
  server/utilities/config.py
  server/utilities/constants/response_messages.py
  server/utilities/prompts/prompt_templates.py
  server/utilities/schema_linking/extract_keyword.py
  server/utilities/schema_linking/schema_linking_utils.py
  server/utilities/schema_linking/value_retrieval.py
  server/utilities/vectorize.py
Labels: enhancement

#52 Return Pruned Schema for all formats
  server/scripts/process_dataset_sequentially.py
  server/utilities/m_schema/schema_engine.py
  server/utilities/prompts/few_shot_prompts.py
  server/utilities/prompts/prompt_factory.py
  server/utilities/utility_functions.py
Labels: enhancement

#55 Injecting descriptions from csvs into M_Schema
  server/utilities/m_schema/schema_engine.py
  server/utilities/utility_functions.py
Labels: enhancement

#54 Feat: Add Schema Selector Prompt and Pruned Schema Script
  server/scripts/add_runtime_pruned_schema.py
  server/utilities/prompts/prompt_templates.py
  server/utilities/schema_linking/extract_keyword.py
  server/utilities/schema_linking/schema_linking_utils.py
Labels: enhancement

#57 Refactor: Minor Fixes in Schema Pruning, Train/Test Split, Google client and and Prune Test
  server/scripts/add_runtime_pruned_schema.py
  server/scripts/prune_test.py
  server/scripts/train_test_split_bird.py
  server/services/google_ai_client.py
  server/utilities/constants/LLM_enums.py
  server/utilities/schema_linking/schema_linking_utils.py
  server/utilities/schema_linking/value_retrieval.py
Labels: bug, enhancement

#58 Implemented Basic XiYan Candidate Selection Prompt
  server/scripts/process_dataset_sequentially.py
  server/utilities/candidate_selection.py
  server/utilities/prompts/prompt_templates.py
Labels: enhancement

#59 Added evidence
  server/scripts/process_dataset_sequentially.py
  server/utilities/prompts/base_prompt.py
  server/utilities/prompts/few_shot_prompts.py
  server/utilities/prompts/prompt_factory.py
  server/utilities/prompts/zero_shot_prompts.py
  server/utilities/vectorize.py
Labels: enhancement

#60 Refactor: Update path config
  server/app/db.py
  server/app/main.py
  server/app/request_schema.py
  server/scripts/add_descriptions_bird_dataset.py
  server/scripts/add_runtime_pruned_schema.py
  server/scripts/bird_eval.py
  server/scripts/cost_estimation_dataset.py
  server/scripts/data_migration_snowflake.py
  server/scripts/download_batch_output.py
  server/scripts/evaluate_cortex_analyst.py
  server/scripts/generate_batch_file.py
  server/scripts/process_batch_output.py
  server/scripts/process_dataset_sequentially.py
  server/scripts/prune_test.py
  server/scripts/train_test_split_bird.py
  server/services/openai_client.py
  server/test/test_main.py
  server/utilities/batch_job.py
  server/utilities/config.py
  server/utilities/constants/script_constants.py
  server/utilities/cost_estimation.py
  server/utilities/m_schema/schema_engine.py
  server/utilities/path_config.py
  server/utilities/prompts/few_shot_prompts.py
  server/utilities/prompts/zero_shot_prompts.py
  server/utilities/schema_linking/schema_linking_utils.py
  server/utilities/schema_linking/value_retrieval.py
  server/utilities/sql_improvement.py
  server/utilities/utility_functions.py
  server/utilities/vectorize.py
Labels: enhancement

#63 Feat: Integrated Pruned Schema into Our SQL Pipeline
  server/app/main.py
  server/scripts/add_descriptions_bird_dataset.py
  server/scripts/process_dataset_sequentially.py
  server/utilities/candidate_selection.py
  server/utilities/m_schema/schema_engine.py
  server/utilities/path_config.py
  server/utilities/prompts/base_prompt.py
  server/utilities/prompts/few_shot_prompts.py
  server/utilities/prompts/prompt_factory.py
  server/utilities/prompts/zero_shot_prompts.py
  server/utilities/schema_linking/schema_linking_utils.py
  server/utilities/sql_improvement.py
  server/utilities/utility_functions.py
  server/utilities/vectorize.py
Labels: enhancement

#62 Xiyan Refiner Prompt
  server/scripts/bird_eval.py
  server/scripts/process_dataset_sequentially.py
  server/utilities/candidate_selection.py
  server/utilities/config.py
  server/utilities/prompts/few_shot_prompts.py
  server/utilities/prompts/prompt_templates.py
  server/utilities/sql_improvement.py
  server/utilities/vectorize.py
Labels: enhancement

#65 Feat: Added ICL XiYan Prompt
  server/utilities/constants/prompts_enums.py
  server/utilities/prompts/few_shot_prompts.py
  server/utilities/prompts/prompt_factory.py
Labels: enhancement

#64 Refactor: Updated Chromadb Client to Persistent Chromadb client
  server/utilities/config.py
  server/utilities/vectorize.py
Labels: enhancement

#66 Fixed Small Bug in Previous merges
  server/utilities/sql_improvement.py
Labels: bug

#69 Feat: Added Alibaba / DashScope client and Qwen model support
  server/services/client_factory.py
  server/services/dashscope_client.py
  server/utilities/config.py
  server/utilities/constants/LLM_enums.py
Labels: enhancement

#68 Feat: Support single prediction file in process_dataset_sequentially
  server/scripts/process_dataset_sequentially.py
  server/utilities/path_config.py
Labels: enhancement

#72 Add gemini/config.yaml
  gemini/config.yaml
Labels: enhancement

#75 Gemini configuration yaml file
  gemini/config.yaml
Labels: enhancement

#76 Gemini configuration updated
  gemini/config.yaml
Labels: enhancement
