Repository Conrad-X/text2SQL, pull requests merged in 2025-01, with the labels that each got.

#31 Implemented Masking from DAIL SQL
  server/scripts/mask_bird.py
  server/utilities/constants/script_constants.py
  server/utilities/masking/linking_process.py
  server/utilities/masking/linking_utils/abstract_preproc.py
  server/utilities/masking/linking_utils/corenlp.py
  server/utilities/masking/linking_utils/utils.py
  server/utilities/masking/masking_requirements.txt
  server/utilities/masking/pretrained_embeddings.py
Labels: enhancement

#34 Feat: Add Google AI Client and Models
  server/services/base_client.py
  server/services/client_factory.py
  server/services/google_ai_client.py
  server/utilities/config.py
  server/utilities/constants/LLM_enums.py
Labels: enhancement

#37 Feat: Add Script for Sequential Processing of Dataset
  server/scripts/process_dataset_sequentially.py
  server/utilities/constants/script_constants.py
  server/utilities/utility_functions.py
Labels: enhancement

#39 Fixed a Bug when saving masked questions
  server/scripts/mask_bird.py
Labels: bug

#38 Feat: Pipeline for adding schema descriptions and improving SQL predictions
  server/scripts/add_descriptions_bird_dataset.py
  server/scripts/data_migration_snowflake.py
  server/scripts/evaluate_cortex_analyst.py
  server/scripts/process_dataset_sequentially.py
  server/utilities/config.py
  server/utilities/constants/prompts_enums.py
  server/utilities/constants/script_constants.py
  server/utilities/prompts/few_shot_prompts.py
  server/utilities/prompts/prompt_factory.py
  server/utilities/prompts/prompt_templates.py
  server/utilities/utility_functions.py
Labels: enhancement

#41 Fix: Adding Missing Logging Utility File
  server/utilities/logging_utils.py
Labels: enhancement

#40 New Train Test and Masking Script
  server/scripts/train_test_split_bird.py
  server/utilities/masking/linking_process.py
  server/utilities/masking/linking_utils/utils.py
Labels: enhancement

#42 Added DeepSeek Client
  server/scripts/process_dataset_sequentially.py
  server/services/client_factory.py
  server/services/deepseek_client.py
  server/utilities/config.py
  server/utilities/constants/LLM_enums.py
Labels: enhancement

#44 Add Config to the train test split
  server/scripts/process_dataset_sequentially.py
  server/scripts/train_test_split_bird.py
Labels: bug, enhancement
